### ISSUE TITLE
Twitter Widget fails to load on HTTPS

### ISSUE THREAD

**Issue by fm** [getgrav/grav-skeleton-ceevee-site#2]
Where does the js code for the twitter widget reside so I can switch that link to https? Widget will fail to load HTTP assets when on HTTPS connection

`Page was loaded over HTTPS, but requested an insecure script 'http://cdn.syndication.twimg.com/widgets/timelines/670642497371168769?&lang…itterFetcher.callback&suppress_response_codes=true&rnd=0.49666471197269857'. This request has been blocked; the content must be served over HTTPS.`

**Comment by hexplor** [comment]
Hey,
Script is located here: templates/partials/twFetcher.html.twig
Let me know if you were able to display widget

**Comment by fm** [comment]
Hey @hexplor,

I was able to display the widget by switching the link to https.

Just a thought - wouldn't it be better to ship the template with the https version of the link? It doesn't hurt non-ssl sites, and would prevent the issue on those who do use https.

**Comment by hexplor** [comment]
Fixed in develop branch (theme). Will be included in next update.
