### ISSUE TITLE
Closing the menu puts you back at the top (mobile)

### ISSUE THREAD

**Issue by makruiten** [getgrav/grav-skeleton-ceevee-site#4]
Closing the menu on mobile (iOS 9.2) puts you back at the top of the page.

**Comment by hexplor** [comment]
Fixed in develop branch of theme: https://github.com/getgrav/grav-theme-ceevee/commit/47a54cfbf7fc80abc1ee593cb38e30abaed44d9d#diff-095695c58b3f38b53edeb21ec235b5e3
