### ISSUE TITLE
Stuck at 'Thank you!' page after submitting form

### ISSUE THREAD

**Issue by makruiten** [getgrav/grav-skeleton-ceevee-site#6]
After submitting a form, the visitor is stuck on the 'Thank you!' page, as there is no link back home.

**Comment by flaviocopes** [comment]
You can customize that page as you want. You can also redirect to any other page on your site by editing the form "display" option. 

The skeleton is just an example to start with.

**Comment by makruiten** [comment]
I'm busy with editing it, but I think this is a navigation issue that shouldn't be there, not even in a skeleton. I get that this is just an example, provided for free by people that spent their own time on it, so I'm not complaining. Having said that, I think for less experienced users (like me) it should at least provide a fully functional starting point, so they can base their site on it and edit it if they get more comfortable with the system. Apart from the navigation issue, I think the message should be more to the top, without the full screen homepage header above it. If I'll manage to get it working nicely, I will generate a pull request.

**Comment by hexplor** [comment]
Fixed in theme develop: https://github.com/getgrav/grav-theme-ceevee/commit/4b1724c1dcb2c69734ebb8eecaf5699853cdcd6b
There's "Home" link at the top also.

**Comment by makruiten** [comment]
Thank you. The home link at the top does not change the page for me. It just adds #home.
